In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

x          y
0  48.955889  60.723602
1  44.687196  82.892504
2  60.297327  97.379897
3  45.618644  48.847153
4  38.816818  56.877213

In [5]:
df.shape

(99, 2)

In [6]:
x = df['x']

In [7]:
y = df['y']

# Step By Step

In [16]:
m = 0
c = 0
Learning_rate = 0.0001

n = int(len(x))

iterations = 100

for i in range(iterations):
    y_predicted = m*x+c
    dervatives_m = (-2/n) * sum(x*(y - y_predicted))
    dervatives_c = (-2/n) * sum((y - y_predicted))
    
    m = m -Learning_rate * dervatives_m 
    c = c - Learning_rate * dervatives_c 
print(m,c)
print('This is m :', m)
print('This is c :', c)

1.4809270431911752 0.03630800912185734
This is m : 1.4809270431911752
This is c : 0.03630800912185734


# Prediction 

In [17]:
x = 38.816818

In [18]:
y = 1.4809270431911752 * x + 0.03630800912185734

In [19]:
y

57.52118351595185

# Agin Linear regression Model Use Gradient Decent

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
reg = LinearRegression()

In [22]:
reg.fit(df[['x']],df[['y']])

LinearRegression()

In [23]:
reg.predict([[38.816818]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[59.87972292]])

In [24]:
reg.coef_

array([[1.28735737]])

In [25]:
reg.intercept_

array([9.90860619])